version: "3"
services:
  web:
    build: .
    ports:
      - "80:4000"
    command: bash start.sh
    environment:
      - MIX_ENV=dev
      - PORT=4000
    volumes:
      - ./:/app
    networks:
      - slack
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    hostname: db
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    networks:
      - slack

networks:
  slack:
